# Generated by Django 3.0.6 on 2020-05-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
    ]
