# Generated by Django 3.0.6 on 2020-05-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_item_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='business.Business'),
        ),
    ]
